version: "3.8"

services:
  redis:
    image: redis:latest
    restart: always

  celery_worker:
    build:
      context: .
      dockerfile: ./celery/worker/Dockerfile
    image: public.ecr.aws/i4v2w1v3/wen-lucky-cron-celery_worker
    container_name: celery_worker
    depends_on:
      - redis
    env_file:
      - .env
    labels:
      - "com.centurylinklabs.watchtower.enable=${PRODUCTION}"
    restart: always

  celery_flower:
    build:
      context: .
      dockerfile: ./celery/flower/Dockerfile
    image: public.ecr.aws/i4v2w1v3/wen-lucky-cron-celery_flower
    container_name: celery_flower
    ports:
      - 5555:5555
    depends_on:
      - celery_worker
    env_file:
      - .env
    labels:
      - "com.centurylinklabs.watchtower.enable=${PRODUCTION}"
    restart: always

  celery_beat:
    build:
      context: .
      dockerfile: ./celery/beat/Dockerfile
    image: public.ecr.aws/i4v2w1v3/wen-lucky-cron-celery_beat
    container_name: celery_beat
    depends_on:
      - celery_worker
    env_file:
      - .env
    labels:
      - "com.centurylinklabs.watchtower.enable=${PRODUCTION}"
    restart: always

  participation_service:
    build:
      context: .
      dockerfile: ./participation_svc/Dockerfile
    image: public.ecr.aws/i4v2w1v3/wen-lucky-cron-participation_service
    container_name: participation_service
    env_file:
      - .env
    labels:
      - "com.centurylinklabs.watchtower.enable=${PRODUCTION}"
    restart: always

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
    command: --interval 30
    restart: always
